Trying the pickle add function but does not function.

In [3]:
# imports
import matplotlib.image as mpimg
import numpy as np
import cv2
import pandas as pd
import pickle
from tensorflow.keras.utils import to_categorical
import os

2022-04-10 21:40:52.902704: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/anthony/.pyenv/versions/3.8.12/envs/tails-and-whales/lib/python3.8/site-packages/cv2/../../lib64:
2022-04-10 21:40:52.902876: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [32]:
def create_X_y(number_of_photos, csv_path = '../raw_data/train_kaggle.csv'): #number of photos could be a parameter
    # load and make changes to csv  
    data = pd.read_csv(csv_path)
    data['speciesv2'] = data['species']
    data['speciesv2'].loc[data['speciesv2'].str.contains('dolphin')] = 'dolphin'
    data['speciesv2'].loc[data['speciesv2'].str.contains('dolpin')] = 'dolphin'
    data['speciesv2'].loc[data['speciesv2'].str.contains('whale')] = 'whale'
    data = data[data['speciesv2'] != 'globis']
    # create and save X in raw-data/X.pkl
    path = "../raw_data/train_images/"
    images_list = list(data['image'])

    # This block code includes a resizing step
    loaded_images = []
    a = 1
    for index, image in enumerate(images_list[:number_of_photos]):   #number of photos [:number_of_photos]
        print(f" processing photo number {a}")

        # resizing image
        img = mpimg.imread(path + image)
        img = cv2.resize(img, dsize=(256, 256), interpolation= cv2.INTER_LINEAR)
        a +=1

        # reshaphe photo in 3D dimension
        if len(img.shape) != 3:
            #list_index_bw.append(index)
            #list_len.append(len(img.shape))
            img = np.stack((img,)*3, axis=-1)

        loaded_images.append(np.array(img))    
  
    # convert to 3D array
    X = np.array(loaded_images)
    print(X.shape)
    # get gcp bucket path

    preprocessed_data_path = "../raw_data/preprocessed_data/"
    # save preprocessed images to GCP bucket
    with open(os.path.join(preprocessed_data_path, 'X_1.pkl'), 'ab') as handle:
        pickle.dump(X, handle)
       
    # create and save y in raw_data/y.pkl
    classes = {'whale':0, 'dolphin':1, 'beluga':2}
    #Add a new column 'class' on data_sample df
    data['class'] = data['speciesv2'].map(classes)
    num_classes = 3
    y = to_categorical(data['class'][:number_of_photos], num_classes=num_classes) #number of photos [:number_of_photos]
    with open(os.path.join(preprocessed_data_path, 'y_1.pkl'), 'ab') as handle:
        pickle.dump(y, handle)

    print("X and y are saved ! Well Done !")


In [33]:
create_X_y(5)

 processing photo number 1
 processing photo number 2
 processing photo number 3
 processing photo number 4
 processing photo number 5
(5, 256, 256, 3)
X and y are saved ! Well Done !


In [34]:
create_X_y(5)

 processing photo number 1
 processing photo number 2
 processing photo number 3
 processing photo number 4
 processing photo number 5
(5, 256, 256, 3)
X and y are saved ! Well Done !


In [35]:
with open("../raw_data/preprocessed_data/X_1.pkl", "rb") as fi:
    X = pickle.load(fi)
X.shape

(5, 256, 256, 3)

In [ ]:
def create_X_y(number_of_photos, csv_path = '../raw_data/train_kaggle.csv'): #number of photos could be a parameter
    # load and make changes to csv  
    data = pd.read_csv(csv_path)
    data['speciesv2'] = data['species']
    data['speciesv2'].loc[data['speciesv2'].str.contains('dolphin')] = 'dolphin'
    data['speciesv2'].loc[data['speciesv2'].str.contains('dolpin')] = 'dolphin'
    data['speciesv2'].loc[data['speciesv2'].str.contains('whale')] = 'whale'
    data = data[data['speciesv2'] != 'globis']
    # create and save X in raw-data/X.pkl
    path = "../raw_data/train_images/"
    images_list = list(data['image'])

    # This block code includes a resizing step
    loaded_images = []
    a = 1
    for index, image in enumerate(images_list[number_of_photos:]):   #number of photos [:number_of_photos]
        print(f" processing photo number {a}")

        # resizing image
        img = mpimg.imread(path + image)
        img = cv2.resize(img, dsize=(256, 256), interpolation= cv2.INTER_LINEAR)
        a +=1

        # reshaphe photo in 3D dimension
        if len(img.shape) != 3:
            #list_index_bw.append(index)
            #list_len.append(len(img.shape))
            img = np.stack((img,)*3, axis=-1)

        loaded_images.append(np.array(img))    
  
    # convert to 3D array
    X = np.array(loaded_images)
    print(X.shape)
    # get gcp bucket path

    preprocessed_data_path = "../raw_data/preprocessed_data/"
    # save preprocessed images to GCP bucket
    with open(os.path.join(preprocessed_data_path, 'X_1.pkl'), 'ab') as handle:
        pickle.dump(X, handle)
       
    # create and save y in raw_data/y.pkl
    classes = {'whale':0, 'dolphin':1, 'beluga':2}
    #Add a new column 'class' on data_sample df
    data['class'] = data['speciesv2'].map(classes)
    num_classes = 3
    y = to_categorical(data['class'][number_of_photos:], num_classes=num_classes) #number of photos [:number_of_photos]
    with open(os.path.join(preprocessed_data_path, 'y_1.pkl'), 'ab') as handle:
        pickle.dump(y, handle)

    print("X and y are saved ! Well Done !")


In [ ]:
create_X_y(25000)

In [4]:
"""with open('../raw_data/preprocessed_data/X_1.npy', 'rb') as f:
    X_1 = np.load(f)
    
with open('../raw_data/preprocessed_data/X_2.npy', 'rb') as g:
    X_2 = np.load(g)"""
    
with open('../raw_data/preprocessed_data/y_1.npy', 'rb') as h:
    y_1 = np.load(h)
    
with open('../raw_data/preprocessed_data/y_2.npy', 'rb') as i:
    y_2 = np.load(i)

In [5]:
print(y_1,y_2)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]] [[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [6]:
y = np.concatenate((y_1,y_2), axis=0)
print(y.shape)

(50917, 3)


In [8]:
preprocessed_data_path = "../raw_data/preprocessed_data/"

with open(os.path.join(preprocessed_data_path, 'y.npy'), 'wb') as f:
    np.save(f, y)

In [1]:
import numpy as np

In [2]:
with open('../raw_data/preprocessed_data/X_1.npy', 'rb') as f:
    X_1 = np.load(f)
    
with open('../raw_data/preprocessed_data/X_2.npy', 'rb') as g:
    X_2 = np.load(g)

In [ ]:
X = np.concatenate((X_1,X_2), axis=0)
print(X.shape)